version: '3.7'

services:

  php-apache-mysqli:
    image: php:7.2-apache-mysqli
    ports:
      - "421:80"
    volumes:
      - "$PWD:/var/www/html"
    networks:
      - fullstack-net

  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3606:3606"
    volumes:
      - "$PWD/sql/config:/etc/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: fullstack
    networks:
      fullstack-net:
        aliases:
          - db  

networks:
  fullstack-net:
    driver: overlay
    attachable: true


    # attaching to mysql instance
    # docker run -it --network fullstack_fullstack-net --rm mysql mysql -hdb -uroot -pfullstack

    # docker exec -i <container_name> sh -c 'exec mysql -uroot -pfullstack' < ./sql/databaseCreation.sql